### ISSUE TITLE
Cache option

### ISSUE THREAD

**Issue by egemon** [iampava/imagemin-webp-webpack-plugin#14]
Thank u for such a great plugin! 
Is there anyway to cache somehow results of this plugin?
If this would be loader I would use cache-loader and thread-loader, but I am not quite sure how to use those with this plugin?
Also not sure how imagemin-loader works with this plugin?

**Comment by iampava** [comment]
Hey! I'm on holiday now, I'll have a look at it next week when I come back :)

**Comment by iampava** [comment]
Hey! Sorry for the very very very long delay, I got caught up in work and totally forgot about this. Sooo, I did some quick research and I guess you want to prevent reconverting all images between builds because it takes a long time.

Would disabling the plugin for the development build do the trick? That way you'll have the conversion happening just on production.

If not, I'm thinking of other ways of implementing this instead of converting the plugin to a loader. How about if I offer a "cache-dir" option, and it will convert only images not found in that dir? Would that work for your usecase?

**Comment by iampava** [comment]
Closed this issue due to inactivity. Feel free to open it if you want to continue the discussion on the problem and how best to solve it.

**Comment by nerikosans** [comment]
Hi @iampava , thank you for a great plugin!
I opened a pull request #76  to add an option to skip unchanged images, which will work like caching results.
I would be so grateful if you can check and review it.

(I don't have the permission to reopen this issue, I'm afraid)
