### ISSUE TITLE
Vulnerability : Memory Exposure in tunnel-agent

### ISSUE THREAD

**Issue by Ghostfly** [iampava/imagemin-webp-webpack-plugin#2]
There is a vulnerability due to tunnel-agent dependency

Please update, or I can PR if you don't have time

**Comment by iampava** [comment]
Hey,

What exactly is the problem? Is `imagemin` or `imagemin-webp` depending on [tunnel-agent](https://www.npmjs.com/package/tunnel-agent) which has a vulnerability?

**Comment by Ghostfly** [comment]
imagemin-webp seems not really active, btw it's not a "big" problem I think

**Comment by iampava** [comment]
Ok, so I ran `npm audit` and discovered the issue.

The question now is how to fix it since `tunnel-agent` is at the bottom of the dependency tree? If you have any ideas please share :)


![vulnerability](https://user-images.githubusercontent.com/11327761/49147511-941f3e00-f30d-11e8-94b6-d8e1f9a613dc.png)
