### ISSUE TITLE
Prevent re-encoding of images into webp during development

### ISSUE THREAD

**Issue by prashantpalikhe** [iampava/imagemin-webp-webpack-plugin#24]
Right now, every time a user saves any file in the codebase during development, it triggers the webp encoding for all images all over again. In projects with a big set of assets, this can be easily take seconds for each save.

It's better to check if an asset has already been converted to webp and only do the conversion if necessary.

**Comment by iampava** [comment]
First of all, sorry for the extremely late delay. I have to admin I totally forgot about this issue. So, sorry again :)

Now, moving on to it, I just tested if the images are re-converted and it seems they are not. I wonder if it's because of updates in other packages... Maybe you could give it a try in the [test-project](https://github.com/iampava/imagemin-webp-webpack-plugin/tree/master/test-project) and see if it replicates there (you can `console.log` inside `plugin.js` and see which files are actually converted)

**Comment by iampava** [comment]
Closing this as it seems to have been a `copy-webpack-plugin` issue.
