### ISSUE TITLE
webpack-dev-server error

### ISSUE THREAD

**Issue by lexa18** [iampava/imagemin-webp-webpack-plugin#6]
Hello! Thank you for the cool plugin. I get an error when working with webpack-dev-server: "WARNING in Cannot read property 'path' of undefined". But when building in production, everything works well.

**Comment by iampava** [comment]
Hey and thanks for the issue submit. I'll investigate the problem over the weekend, when I get some free time and then get back to you ;)

**Comment by dkrnl** [comment]
catch similar bug

**Comment by iampava** [comment]
I did some improvements and quite a lot of refactoring and the issue should be fixed now. :)

I did a push on GitHub https://github.com/iampava/imagemin-webp-webpack-plugin/commit/7409e6f16af32f3e0517a00e6d53c4b738240e21 but not a publish on NPM yet. I'm waiting for your feedback to tell me if it actually works in your projects before going public.

PS: to try the latest code just replace the contents directly in node_modules
PPS: since the plugin order matters for Webpack, try and put this plugin last

**Comment by lexa18** [comment]
Good job. Works without errors. Thank you very much!

**Comment by iampava** [comment]
Great! @dkrnl, @smajl  can you confirm it now works in your projects?

**Comment by iampava** [comment]
Published v3.0.0 with the fix on NPM!

**Comment by smajl** [comment]
@iampava Tested 3.0.0 and it works flawlessly, thank you.
